"""Seed the ISO/IEC 27001:2022 Annex A baseline controls into the control catalog.

Revision ID: 0003_seed_iso27001_annex_a
Revises: 0002_confidence_workflow
"""

from alembic import op
import sqlalchemy as sa

revision = "0003_seed_iso27001_annex_a"
down_revision = "0002_confidence_workflow"
branch_labels = None
depends_on = None


def upgrade():
    control_table = sa.table(
        "control_catalog",
        sa.column("framework_name", sa.String),
        sa.column("framework_version", sa.String),
        sa.column("control_id", sa.String),
        sa.column("control_family", sa.String),
        sa.column("title", sa.String),
        sa.column("description", sa.Text),
        sa.column("objective", sa.Text),
        sa.column("evidence_examples", sa.JSON),
        sa.column("scanner_signals", sa.JSON),
        sa.column("keywords", sa.JSON),
        sa.column("source_url", sa.String),
        sa.column("active_status", sa.Boolean),
    )

    controls = [
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.5.1",
            "control_family": "Organizational",
            "title": "Information Security Policies",
            "description": "Establish, approve, communicate, review, and update information security policies and supporting procedures.",
            "objective": "Provide a formal policy baseline for information security governance and management expectations.",
            "evidence_examples": ["approved_information_security_policy.pdf", "policy_review_log.xlsx", "security_policy_acknowledgment_records"],
            "scanner_signals": ["policy", "security_policy", "wiki", "documentation"],
            "keywords": ["policy", "governance", "information security"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/5-1-information-security-policies-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.5.2",
            "control_family": "Organizational",
            "title": "Information Security Roles and Responsibilities",
            "description": "Define and document information security roles, responsibilities, and authorities to ensure accountability.",
            "objective": "Ensure that all relevant security responsibilities are assigned, understood, and enforced.",
            "evidence_examples": ["roles_and_responsibilities_matrix", "onboarding_checklist", "security_org_chart"],
            "scanner_signals": ["iam", "team_roles", "owner", "responsible"],
            "keywords": ["roles", "responsibilities", "accountability"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/5-2-information-security-roles-responsibilities-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.5.3",
            "control_family": "Organizational",
            "title": "Segregation of Duties",
            "description": "Separate incompatible duties and responsibilities to reduce the risk of unauthorized or unintentional changes.",
            "objective": "Prevent conflicts of interest and limit the impact of a single individual on critical processes.",
            "evidence_examples": ["sox_risk_matrix", "privileged_access_review", "approval_workflow"],
            "scanner_signals": ["segregation", "approval", "privileged_access"],
            "keywords": ["segregation of duties", "separation", "approval"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/5-3-segregation-of-duties-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.5.9",
            "control_family": "Organizational",
            "title": "Inventory of Information and Other Associated Assets",
            "description": "Maintain an inventory of information and associated assets to support security protection and risk management.",
            "objective": "Ensure visibility of information assets required to assess risk, allocate protection, and support incident response.",
            "evidence_examples": ["asset_inventory.csv", "data_catalog", "service_inventory"],
            "scanner_signals": ["asset_inventory", "resource_list", "inventory"],
            "keywords": ["inventory", "asset management", "catalog"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/5-9-inventory-of-information-other-associated-assets-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.5.12",
            "control_family": "Organizational",
            "title": "Classification of Information",
            "description": "Classify information according to its value, legal requirements, sensitivity, and criticality.",
            "objective": "Ensure appropriate handling, retention, and protection based on information classification.",
            "evidence_examples": ["data_classification_policy", "classification_scheme", "sensitivity_labels"],
            "scanner_signals": ["classification", "sensitivity", "label"],
            "keywords": ["classification", "sensitivity", "labels"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/5-12-classification-of-information-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.5.15",
            "control_family": "Organizational",
            "title": "Access Control",
            "description": "Limit access to information and systems based on business and security requirements.",
            "objective": "Prevent unauthorized access to systems, applications, data, and services.",
            "evidence_examples": ["rbac_policy", "access_review_report", "least_privilege_configuration"],
            "scanner_signals": ["access_control", "iam", "rbac", "permission"],
            "keywords": ["access control", "permissions", "least privilege"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/5-15-access-control-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.5.16",
            "control_family": "Organizational",
            "title": "Identity Management",
            "description": "Ensure the provision, modification, and revocation of user identities and access rights are controlled and auditable.",
            "objective": "Maintain reliable and traceable identity lifecycle management for human and system accounts.",
            "evidence_examples": ["identity_lifecycle_policy", "joiner_mover_leaver_process", "provisioning_audit"],
            "scanner_signals": ["identity", "provisioning", "user_management"],
            "keywords": ["identity", "provisioning", "joiner mover leaver"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/5-16-identity-management-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.5.17",
            "control_family": "Organizational",
            "title": "Authentication Information",
            "description": "Protect authentication information such as passwords, tokens, and secrets from disclosure and unauthorized use.",
            "objective": "Reduce the risk of credential compromise and ensure secure authentication mechanisms are used.",
            "evidence_examples": ["password_policy", "secret_rotation_log", "mfa_enforcement_report"],
            "scanner_signals": ["authentication", "password", "mfa", "secret"],
            "keywords": ["authentication", "password", "mfa"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/5-17-authentication-information-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.5.18",
            "control_family": "Organizational",
            "title": "Access Rights",
            "description": "Grant, review, and remove access rights based on approved business and security requirements.",
            "objective": "Ensure users and systems retain only the minimum necessary access for their roles.",
            "evidence_examples": ["access_request_records", "quarterly_access_review", "privileged_account_listing"],
            "scanner_signals": ["access_rights", "privileged_access", "review"],
            "keywords": ["access rights", "privileged users", "review"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/5-18-access-rights-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.5.24",
            "control_family": "Organizational",
            "title": "Information Security Incident Management Planning and Preparation",
            "description": "Prepare for information security incidents with defined roles, procedures, communications, and escalation paths.",
            "objective": "Reduce the impact of incidents by ensuring that teams can respond quickly and consistently.",
            "evidence_examples": ["incident_response_plan", "escalation_matrix", "tabletop_exercise_results"],
            "scanner_signals": ["incident_response", "playbook", "escalation"],
            "keywords": ["incident response", "planning", "preparedness"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/5-24-incident-management-planning-and-preparation-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.5.31",
            "control_family": "Organizational",
            "title": "Legal, Statutory, Regulatory and Contractual Requirements",
            "description": "Identify and comply with legal, statutory, regulatory, and contractual requirements relevant to information security.",
            "objective": "Ensure compliance obligations are understood and reflected in security controls and operations.",
            "evidence_examples": ["regulatory_matrix", "contract_review", "compliance_policy"],
            "scanner_signals": ["compliance", "legal", "contractual"],
            "keywords": ["regulatory", "legal", "contractual"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/5-31-legal-statutory-regulatory-contractual-requirements-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.5.34",
            "control_family": "Organizational",
            "title": "Privacy and Protection of PII",
            "description": "Protect Personally Identifiable Information (PII) through appropriate handling, access, retention, and disposal controls.",
            "objective": "Preserve privacy and reduce the risk of unauthorized exposure of personal data.",
            "evidence_examples": ["privacy_notice", "pii_inventory", "retention_schedule"],
            "scanner_signals": ["privacy", "pii", "data_protection"],
            "keywords": ["privacy", "PII", "data protection"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/5-34-privacy-and-protection-of-pii-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.6.1",
            "control_family": "People",
            "title": "Screening",
            "description": "Screen personnel before granting access to information systems or facilities.",
            "objective": "Reduce the risk of insider threats by evaluating the suitability of personnel before onboarding.",
            "evidence_examples": ["background_check_policy", "screening_records", "hiring_checklist"],
            "scanner_signals": ["screening", "hiring", "background_check"],
            "keywords": ["screening", "background check", "onboarding"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/6-1-screening-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.6.3",
            "control_family": "People",
            "title": "Information Security Awareness, Education and Training",
            "description": "Ensure users receive appropriate awareness, education, and training about information security responsibilities.",
            "objective": "Improve security behavior and ensure personnel understand their role in protecting information and systems.",
            "evidence_examples": ["security_awareness_training", "completion_reports", "phishing_simulation_results"],
            "scanner_signals": ["training", "awareness", "phishing"],
            "keywords": ["awareness", "training", "phishing"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/6-3-information-security-awareness-education-training-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.6.7",
            "control_family": "People",
            "title": "Remote Working",
            "description": "Protect information when personnel work remotely and use personal or unmanaged devices.",
            "objective": "Maintain security protections for remote workers and reduce risk transmitted over unmanaged environments.",
            "evidence_examples": ["remote_access_policy", "vpn_configuration", "device_compliance_report"],
            "scanner_signals": ["remote", "vpn", "home_office"],
            "keywords": ["remote work", "VPN", "home office"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/6-7-remote-working-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.7.1",
            "control_family": "Physical",
            "title": "Physical Security Perimeters",
            "description": "Implement physical barriers to protect information systems and sensitive areas from unauthorized access.",
            "objective": "Prevent unauthorized physical entry to sites, rooms, and critical infrastructure.",
            "evidence_examples": ["site_access_map", "badge_access_logs", "perimeter_review"],
            "scanner_signals": ["physical", "badge", "perimeter"],
            "keywords": ["physical security", "perimeter", "access control"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/7-1-physical-security-perimeters-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.7.10",
            "control_family": "Physical",
            "title": "Storage Media",
            "description": "Protect storage media against unauthorized access, loss, theft, and corruption.",
            "objective": "Ensure sensitive data stored on media is secured throughout its lifecycle.",
            "evidence_examples": ["encrypted_usb_policy", "media_destruction_log", "storage_media_inventory"],
            "scanner_signals": ["storage", "encrypted", "media"],
            "keywords": ["storage media", "encryption", "destruction"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/7-10-storage-media-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.8.2",
            "control_family": "Technological",
            "title": "Privileged Access Rights",
            "description": "Restrict, monitor, and review privileged access to critical systems and data.",
            "objective": "Reduce the impact of administrative misuse or compromise of privileged accounts.",
            "evidence_examples": ["privileged_access_policy", "admin_account_inventory", "access_review_results"],
            "scanner_signals": ["privileged", "admin", "sudo", "root"],
            "keywords": ["privileged access", "administrator", "root"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/8-2-use-of-privileged-access-rights-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.8.5",
            "control_family": "Technological",
            "title": "Secure Authentication",
            "description": "Use secure authentication mechanisms to protect system access from unauthorized use.",
            "objective": "Ensure authentication is strong, manageable, and resistant to common credential attacks.",
            "evidence_examples": ["mfa_policy", "authentication_configuration", "failed_login_report"],
            "scanner_signals": ["mfa", "auth", "password_policy"],
            "keywords": ["authentication", "MFA", "single sign-on"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/8-5-secure-authentication-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.8.7",
            "control_family": "Technological",
            "title": "Protection Against Malware",
            "description": "Protect information systems against malware through preventive, detective, and corrective controls.",
            "objective": "Reduce the risk of malware infection and related operational disruption.",
            "evidence_examples": ["endpoint_protection_dashboard", "malware_detection_alerts", "update_policy"],
            "scanner_signals": ["malware", "antivirus", "edr"],
            "keywords": ["malware", "antivirus", "endpoint"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/8-7-protection-against-malware-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.8.13",
            "control_family": "Technological",
            "title": "Information Backup",
            "description": "Implement backup procedures to protect information and support recovery from incidents or failures.",
            "objective": "Ensure reliable recovery of systems, applications, and data when disruptions occur.",
            "evidence_examples": ["backup_policy", "backup_job_report", "recovery_test_results"],
            "scanner_signals": ["backup", "recovery", "restore"],
            "keywords": ["backup", "recovery", "restore"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/8-13-information-backup-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.8.20",
            "control_family": "Technological",
            "title": "Network Security",
            "description": "Protect networks and network services through appropriate technical and organizational controls.",
            "objective": "Reduce unauthorized access to network resources and limit lateral movement across systems.",
            "evidence_examples": ["network_acl_rules", "firewall_policy", "segmented_subnet_design"],
            "scanner_signals": ["network", "firewall", "nsg", "subnet"],
            "keywords": ["network security", "firewall", "network segmentation"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/8-20-network-security-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.8.24",
            "control_family": "Technological",
            "title": "Use of Cryptography",
            "description": "Use cryptographic controls to protect the confidentiality, integrity, and authenticity of information.",
            "objective": "Ensure data in transit and at rest is appropriately protected using cryptographic methods.",
            "evidence_examples": ["tls_configuration", "key_management_policy", "encryption_standard"],
            "scanner_signals": ["encryption", "tls", "cryptography"],
            "keywords": ["encryption", "cryptography", "TLS"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/8-24-use-of-cryptography-2022/",
            "active_status": True,
        },
        {
            "framework_name": "ISO/IEC 27001:2022 Annex A",
            "framework_version": "2022",
            "control_id": "A.8.32",
            "control_family": "Technological",
            "title": "Change Management",
            "description": "Manage changes to information systems in a controlled and authorized manner.",
            "objective": "Reduce the risk of operational disruption, security regression, and unauthorized changes.",
            "evidence_examples": ["change_approval_records", "change_calendar", "deployment_pipeline_policy"],
            "scanner_signals": ["change", "deployment", "pipeline"],
            "keywords": ["change management", "deployment", "approval"],
            "source_url": "https://www.isms.online/iso-27001/annex-a-2022/8-32-change-management-2022/",
            "active_status": True,
        },
    ]

    op.bulk_insert(control_table, controls)


def downgrade():
    op.execute(
        "DELETE FROM control_catalog WHERE framework_name = 'ISO/IEC 27001:2022 Annex A'"
    )
